# SPDX-License-Identifier: MIT
---
# Sub-playbook to potentially destroy and revert a virtual machine, based on
# settings stored in variable files and on the command line.
#
# See README.md for the actual warnings, but consider yourself warned.

- name: Reboot and revert to the snapshot {{ vm_revert_snapshot }}
  ansible.builtin.include_tasks: do-revert.yml
  when: vm_revert | bool

- name: Reload facts
  ansible.builtin.setup:
    gather_subset:
      - all
  when:
    - vm_revert | bool
    - vm_regather_facts | bool
